kind: pipeline
type: kubernetes
name: default

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: tag
    image: alpine
    commands:
      - test "${DRONE_BRANCH}" == "main" && echo -n "latest," > .tags || true
      - test -n "${DRONE_BRANCH}" && test "${DRONE_BRANCH}" != "main" && echo -n "${DRONE_BRANCH}," > .tags || true
      - test -n "${DRONE_TAG}" && echo -n "${DRONE_TAG}," >> .tags || true
      - sed -i "s/,$//" .tags

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: quay.io/utilitywarehouse/kea-dhcp4
      registry: quay.io
